### PR TITLE
Remove File::Copy::Recursive from Makefile.PL.

### PR DESCRIPTION
**Pull request by jkeenan**
This was overlooked in 5ed42c2 (which was merged in b68dd34).

### CODE REVIEW

**Comment by haarg** [comment]
It wasn't overlooked.  `Makefile.PL` is a build artifact that gets updated by `Dist::Zilla`.

**Comment by garu** [comment]
@jkeenan @haarg thanks! I'll update dist.ini (and hopefully Makefile.PL) and make a new release.

I'll close this as soon as the new release is made and we are sure FCR is gone forever from this dist.

**Comment by eserte** [comment]
So I guess this PR is obsolete and may be closed without a merge?

**Comment by jkeenan** [comment]
> So I guess this PR is obsolete and may be closed without a merge?

There has been no new release of CPAN-Reporter since Jun 21, 2016.  My own practice is not to close p.r.s until a new CPAN release for a distro is available -- but the cpan-testers team is free to adopt any suitable approach.

Thank you very much.
Jim Keenan

**Comment by garu** [comment]
Thank you. 1.2019 is on its way to CPAN and the file is fixed now.

**Pull request closed without merging**
